# Pandas Library

In [297]:
# imports
import pandas as pd

**Read Data From CSV**

In [298]:
df: pd.DataFrame = pd.read_csv("top_10_countries.csv")
df

   Rank        Country             Region  Population  % of world       Date
0     1          India      Southern Asia  1450935791       17.76  15-Mar-24
1     2          China       Eastern Asia  1419321278       17.39  22-Jul-23
2     3  United States   Northern America   345426571        4.23  10-Nov-24
3     4      Indonesia  Southeastern Asia   283487931        3.47  05-Feb-23
4     5       Pakistan      Southern Asia   251269164        3.08  18-Aug-24
5     6        Nigeria     Western Africa   232679478        2.85  30-Apr-23
6     7         Brazil      South America   211998573        2.60  12-Jun-24
7     8     Bangladesh      Southern Asia   173562364        2.13  25-Sep-23
8     9         Russia     Eastern Europe   144820423        1.77  07-Jan-24
9    10       Ethiopia     Eastern Africa   132059767        1.62  19-Oct-23

**`head()`** — Returns the first `n` rows (default 5). Useful for a quick peek at the start of the dataset.

**`tail()`** — Returns the last `n` rows (default 5). Useful for a quick peek at the end of the dataset.

**`sample()`** — Returns `n` random rows from the dataset. Useful for random sampling without bias.

In [299]:
df.head()

   Rank        Country             Region  Population  % of world       Date
0     1          India      Southern Asia  1450935791       17.76  15-Mar-24
1     2          China       Eastern Asia  1419321278       17.39  22-Jul-23
2     3  United States   Northern America   345426571        4.23  10-Nov-24
3     4      Indonesia  Southeastern Asia   283487931        3.47  05-Feb-23
4     5       Pakistan      Southern Asia   251269164        3.08  18-Aug-24

In [300]:
df.tail()

   Rank     Country          Region  Population  % of world       Date
5     6     Nigeria  Western Africa   232679478        2.85  30-Apr-23
6     7      Brazil   South America   211998573        2.60  12-Jun-24
7     8  Bangladesh   Southern Asia   173562364        2.13  25-Sep-23
8     9      Russia  Eastern Europe   144820423        1.77  07-Jan-24
9    10    Ethiopia  Eastern Africa   132059767        1.62  19-Oct-23

In [301]:
df.sample(2)

   Rank    Country             Region  Population  % of world       Date
6     7     Brazil      South America   211998573        2.60  12-Jun-24
3     4  Indonesia  Southeastern Asia   283487931        3.47  05-Feb-23

**total rows and columns**

In [302]:
df.shape

(10, 6)

**Data Set Info**

In [303]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rank        10 non-null     int64
 1   Country     10 non-null     str
 2   Region      10 non-null     str
 3   Population  10 non-null     int64
 4   % of world  10 non-null     float64
 5   Date        10 non-null     str
dtypes: float64(1), int64(2), str(3)
memory usage: 612.0 bytes

**`describe()`** Quick Analysis

In [304]:
df.describe()

           Rank    Population  % of world
count  10.00000  1.000000e+01   10.000000
mean    5.50000  4.645561e+08    5.690000
std     3.02765  5.155369e+08    6.312823
min     1.00000  1.320598e+08    1.620000
25%     3.25000  1.831714e+08    2.247500
50%     5.50000  2.419743e+08    2.965000
75%     7.75000  3.299419e+08    4.040000
max    10.00000  1.450936e+09   17.760000

**Read Single Column**

In [305]:
df["Date"]

0    15-Mar-24
1    22-Jul-23
2    10-Nov-24
3    05-Feb-23
4    18-Aug-24
5    30-Apr-23
6    12-Jun-24
7    25-Sep-23
8    07-Jan-24
9    19-Oct-23
Name: Date, dtype: str

**Read Multiple Columns**

In [306]:
df[["Rank","Date"]]

   Rank       Date
0     1  15-Mar-24
1     2  22-Jul-23
2     3  10-Nov-24
3     4  05-Feb-23
4     5  18-Aug-24
5     6  30-Apr-23
6     7  12-Jun-24
7     8  25-Sep-23
8     9  07-Jan-24
9    10  19-Oct-23

**Get columns name**

In [307]:
df.columns

Index(['Rank', 'Country', 'Region', 'Population', '% of world', 'Date'], dtype='str')

**Get Data Types of Columns**

In [308]:
df.dtypes

Rank            int64
Country           str
Region            str
Population      int64
% of world    float64
Date              str
dtype: object

**Rename Column(s) name**

In [309]:
df.rename(columns={"Country": "Depedency"})

   Rank      Depedency             Region  Population  % of world       Date
0     1          India      Southern Asia  1450935791       17.76  15-Mar-24
1     2          China       Eastern Asia  1419321278       17.39  22-Jul-23
2     3  United States   Northern America   345426571        4.23  10-Nov-24
3     4      Indonesia  Southeastern Asia   283487931        3.47  05-Feb-23
4     5       Pakistan      Southern Asia   251269164        3.08  18-Aug-24
5     6        Nigeria     Western Africa   232679478        2.85  30-Apr-23
6     7         Brazil      South America   211998573        2.60  12-Jun-24
7     8     Bangladesh      Southern Asia   173562364        2.13  25-Sep-23
8     9         Russia     Eastern Europe   144820423        1.77  07-Jan-24
9    10       Ethiopia     Eastern Africa   132059767        1.62  19-Oct-23

**`iloc`** Get the row based on index

In [310]:
df.iloc[3]

Rank                          4
Country               Indonesia
Region        Southeastern Asia
Population            283487931
% of world                 3.47
Date                  05-Feb-23
Name: 3, dtype: object

**`iloc`** Get Range of rows

In [311]:
df.iloc[3:5]

   Rank    Country             Region  Population  % of world       Date
3     4  Indonesia  Southeastern Asia   283487931        3.47  05-Feb-23
4     5   Pakistan      Southern Asia   251269164        3.08  18-Aug-24

**Reverse Order**

In [312]:
df.iloc[::-1]

   Rank        Country             Region  Population  % of world       Date
9    10       Ethiopia     Eastern Africa   132059767        1.62  19-Oct-23
8     9         Russia     Eastern Europe   144820423        1.77  07-Jan-24
7     8     Bangladesh      Southern Asia   173562364        2.13  25-Sep-23
6     7         Brazil      South America   211998573        2.60  12-Jun-24
5     6        Nigeria     Western Africa   232679478        2.85  30-Apr-23
4     5       Pakistan      Southern Asia   251269164        3.08  18-Aug-24
3     4      Indonesia  Southeastern Asia   283487931        3.47  05-Feb-23
2     3  United States   Northern America   345426571        4.23  10-Nov-24
1     2          China       Eastern Asia  1419321278       17.39  22-Jul-23
0     1          India      Southern Asia  1450935791       17.76  15-Mar-24

**Get specific value from a cell using `iloc`**

In [313]:
df.iloc[2,3]

np.int64(345426571)

**Filtration on the whole data set for a specific value**

In [314]:
df == "Pakistan"

    Rank  Country  Region  Population  % of world   Date
0  False    False   False       False       False  False
1  False    False   False       False       False  False
2  False    False   False       False       False  False
3  False    False   False       False       False  False
4  False     True   False       False       False  False
5  False    False   False       False       False  False
6  False    False   False       False       False  False
7  False    False   False       False       False  False
8  False    False   False       False       False  False
9  False    False   False       False       False  False

**Filtration on the whole data set for a specific value along with the data**

In [315]:
df[df["Country"] == "Pakistan"]

   Rank   Country         Region  Population  % of world       Date
4     5  Pakistan  Southern Asia   251269164        3.08  18-Aug-24

**Multiple Filtration**

In [316]:
df[(df["Region"] == "Eastern Europe") | (df["Region"] == "Southern Asia")]

   Rank     Country          Region  Population  % of world       Date
0     1       India   Southern Asia  1450935791       17.76  15-Mar-24
4     5    Pakistan   Southern Asia   251269164        3.08  18-Aug-24
7     8  Bangladesh   Southern Asia   173562364        2.13  25-Sep-23
8     9      Russia  Eastern Europe   144820423        1.77  07-Jan-24